language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules

services:
  - mongodb
  - redis-server

script:
  - npm install
  - cd frontend && npm install
  - npm start
  - cd frontend && npm start
  - cd frontend && npm test
