language: node_js
node_js:
  - "8.10.0"
cache:
  directories:
    - node_modules
    - frontend/node_modules

services:
  - mongodb
  - redis-server

install:
  - npm install

script:
  - npm test

after_script:
  - cd frontend

before_deploy: 
  - npm install
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: frontend/build
  on:
    branch: 44-test-api