language: node_js
node_js:
  - "8.10.0"

addons:
  chrome: stable
  sonarcloud:
    organization: "rafaelnsantos-github"

cache:
  directories:
    - node_modules
    - frontend/node_modules

services:
  - mongodb
  - redis-server

install:
  - npm install
  - cd frontend
  - npm install
  - cd ..

script:
  - npm test
  - cd frontend
  - npm run build_testing
  - npm test
  - cd ..
  - sonar-scanner

after_success:
  - curl -X POST -d {} https://api.netlify.com/build_hooks/$NETLIFY_BUILD_TOKEN

before_deploy:
  - cd frontend
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: frontend/build
  on:
    branch: 48-i18n