language: node_js
node_js:
  - "8.10.0"
cache:
  directories:
  - node_modules

services:
  - mongodb
  - redis-server

before_install: cd frontend

install:
  - npm install

script:
  - npm build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: 42-cloud