language: node_js
node_js:
  - "8.10.0"
cache:
  directories:
  - node_modules

services:
  - mongodb
  - redis-server

install:
  - npm install
  - cd frontend && npm install

script:
  - npm start
  - cd frontend && npm start
  - cd frontend && npm test
