language: node_js
node_js:
  - "8.10.0"

addons:
  chrome: stable

cache:
  directories:
    - node_modules
    - frontend/node_modules

services:
  - mongodb
  - redis-server

install:
  - npm install
  - cd frontend
  - npm install
  - cd ..

script:
  - npm test
  - cd frontend
  # - npm test

before_deploy:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: frontend/build
  on:
    branch: 45-recaptcha